Use 'echo' instead of 'printf' for most basic cases.
'echo' is still POSIX as long as it's being used with no options.

diff --git a/src/lib/bdb/test/Makefile b/src/lib/bdb/test/Makefile
--- a/src/lib/bdb/test/Makefile
+++ b/src/lib/bdb/test/Makefile
@@ -26,10 +26,10 @@ test: .passed
 
 .passed:
 	@for i in $(PROGRAMS); do \
-	    printf "Running test '$$i'.\n"; \
+	    echo "Running test '$$i'."; \
 	    (./$$i && exit); \
 	    if [ $$? -ne 0 ]; then \
-	        printf "Tests failed!\n"; exit 1; \
+	        echo "Tests failed!"; exit 1; \
 	    fi \
 	done
 	touch .passed
